#!/bin/sh

# POSIX compliant implementation
# https://stackoverflow.com/a/52586842
if [ "$(id -u)" -ne 0 ];then
	echo "Requires root!"
	exec sudo "$0" "$@"
	# Automatically rerun script with root
fi



mktemp="$(command -v mktemp)"
crontab="$(command -v crontab)"
cat="$(command -v cat)"
curl="$(command -v curl)"
sha256sum="$(command -v sha256sum)"


TMPDIR="$($mktemp -d)"
trap 'rm -rf -- "$TMPDIR"' EXIT


# downloadFile url sha256sum save-path
downloadFile() {
	url="$1"
	shasum="$2"
	saveTo="$3"

	file="$($mktemp -p $TMPDIR)"
	$curl -f $1 -o $file
	
	if [ "$?" -ne 0 ]; then
		echo "Could not download file from: $url"
		exit 1
	fi
	
	echo "$shasum $file" | $sha256sum --status -c

	if [ "$?" -ne 0 ]; then
		echo "Failed to validate file from: $url"
		echo "File sha256sum mismatch!"
		echo "Wanted: $($sha256sum $file)"
		echo "But got: $shasum"
		exit 2
	fi
	
	echo "installing to: $saveTo"
	cp $file $saveTo
}

baseUrl="https://raw.githubusercontent.com/MidnightRocket/linux-update-scripts/main/debian"



# --- Download updater 

baseName="updateroutine"
updateFile="/usr/local/sbin/$baseName"
downloadFile ${baseUrl}/$baseName b6dc375e3eaf168723c4a9c8cb0b7004d0d55b4e68641feebc0308822234600d $updateFile

chmod +rx $updateFile


serviceUnit="weekly-update.service"
baseName="$serviceUnit"
file="/etc/systemd/system/$baseName"
downloadFile ${baseUrl}/systemd/$baseName 9ac112574e9ff54c3e1b0c67861f7ce262c8bebe86c21f6aa970c1416358c1c6 $file

timerUnit="weekly-update.timer"
baseName="$timerUnit"
file="/etc/systemd/system/$baseName"
downloadFile ${baseUrl}/systemd/$baseName 23feea81fe8d800dc14e4d02a903bbaf23c3ffc14d54e586b8d8f046cb8259d7 $file


systemctl="$(command -v systemctl)"
$systemctl enable --now $timerUnit
$systemctl status $timerUnit

echo 
echo "To run update now use:" 
echo "\tsudo systemctl start $serviceUnit"
echo
echo "To view logs use: "
echo "\tsudo journalctl -f -b -u $serviceUnit"

echo
echo "To disable automatic update use" 
echo "\tsudo systemctl disable $timerUnit"
echo "and to cancel current timer use"
echo "\tsudo systemctl stop $timerUnit"
