#!/bin/sh

# --- README --- #
# to run use 
# curl -fsSL https://raw.githubusercontent.com/MidnightRocket/linux-update-scripts/main/debian/install | sudo sh
#
#
# --- --- ---

# POSIX compliant implementation
# https://stackoverflow.com/a/52586842
if [ "$(id -u)" -ne 0 ];then
	echo "Requires root!"
	exec sudo "$0" "$@"
	# Automatically rerun script with root
fi



mktemp="$(command -v mktemp)"
cat="$(command -v cat)"
curl="$(command -v curl)"
sha256sum="$(command -v sha256sum)"


TMPDIR="$($mktemp -d)"
trap 'rm -rf -- "$TMPDIR"' EXIT


# downloadFile url sha256sum save-path
downloadFile() {
	url="$1"
	shasum="$2"
	saveTo="$3"

	tmpFile="$($mktemp -p $TMPDIR)"
	$curl -f $1 -o $tmpFile
	
	if [ "$?" -ne 0 ]; then
		echo "Could not download file from: $url"
		exit 1
	fi
	
	echo "$shasum $tmpFile" | $sha256sum --status -c

	if [ "$?" -ne 0 ]; then
		echo "Failed to validate file from: $url"
		echo "File sha256sum mismatch!"
		echo "Wanted: $($sha256sum $tmpFile)"
		echo "But got: $shasum"
		exit 2
	fi
	
	echo "installing to: $saveTo"
	cp $tmpFile $saveTo
}

baseUrl="https://raw.githubusercontent.com/MidnightRocket/linux-update-scripts/main/debian"



# --- Download updater 

baseName="updateroutine"
updateFile="/usr/local/sbin/$baseName"
downloadFile ${baseUrl}/$baseName 8f23c91b4421f6a527a2f961cc6504163a8186eaf0a645bd841402647aafdccd $updateFile


chmod 755 "$updateFile"



# --- Create hook directory

configDir="/etc/updateroutine"
hooksDir="${configDir}/hooks"

if [ ! -d "$configDir" ]; then
	echo "Creating config dir in: $configDir"
	mkdir $configDir
	chmod 755 "$configDir"
fi

if [ ! -d "$hooksDir" ]; then 
	mkdir $hooksDir
	chmod 755 "$hooksDir"

	baseName="pre-apt-hook"
	file="$hooksDir/$baseName"
	downloadFile ${baseUrl}/hooks/$baseName da8ac8ff8e672a477a1dc18c97f340868ffa97b1bf43e0883c24ad111f5d586e $file
	chmod 755 "$file"
	echo "Created file $file"

	baseName="post-apt-hook"
	file="$hooksDir/$baseName"
	downloadFile ${baseUrl}/hooks/$baseName 51f8d50d4000d59491d4628037da575fd69182f6a0e6f0c631848c7a5738cc2e $file
	chmod 755 "$file"
	echo "Created file $file"
fi










# --- Download systemd unit files
unitsDir="/etc/systemd/system"

serviceUnit="weekly-update.service"
baseName="$serviceUnit"
file="$unitsDir/$baseName"
downloadFile ${baseUrl}/systemd/$baseName c9152f46513d12000ce1bfd6d31eccf80cd7c07c91c4d0b27eb3bb982430012d $file

timerUnit="weekly-update.timer"
baseName="$timerUnit"
file="$unitsDir/$baseName"
downloadFile ${baseUrl}/systemd/$baseName 23feea81fe8d800dc14e4d02a903bbaf23c3ffc14d54e586b8d8f046cb8259d7 $file


systemctl="$(command -v systemctl)"
$systemctl enable --now $timerUnit
$systemctl status $timerUnit

echo 
echo "To run update now use:" 
echo "\tsudo systemctl start $serviceUnit"
echo
echo "To view logs use: "
echo "\tsudo journalctl -f -b -u $serviceUnit"

echo
echo "To disable automatic update use" 
echo "\tsudo systemctl disable $timerUnit"
echo "and to cancel current timer use"
echo "\tsudo systemctl stop $timerUnit"
