#!/bin/sh

# POSIX compliant implementation
# https://stackoverflow.com/a/52586842
if [ "$(id -u)" -ne 0 ];then
	echo "Requires root!"
	exec sudo "$0" "$@"
	# Automatically rerun script with root
fi



date="$(command -v date)"
tail="$(command -v tail)"

logFile="/var/log/updateroutine.log"
echo "Updating: $($date +'%a %e %b %4Y %H:%M')" >> $logFile
# Trim log file to 25 lines
# https://unix.stackexchange.com/a/310871
echo "$($tail -n 25 $logFile)" > $logFile




apt="$(command -v apt)"
wall="$(command -v wall)"


$apt update -y
$apt full-upgrade -y
$apt autoclean -y
$apt autoremove -y



time="1"
wall -n "System reboot in $time minute(s)"

shutdown -r +$time

