#!/bin/sh

# POSIX compliant implementation
# https://stackoverflow.com/a/52586842
if [ "$(id -u)" -ne 0 ];then
	echo "Requires root!"
	exec sudo "$0" "$@"
	# Automatically rerun script with root
fi

apt="$(command -v apt)"
wall="$(command -v wall)"


$apt update -y
$apt full-upgrade -y
$apt autoclean -y
$apt autoremove -y



time="1"
wall -n "System reboot in $time minute(s)"

shutdown -r +$time

