#!/bin/sh

# POSIX compliant implementation
# https://stackoverflow.com/a/52586842
if [ "$(id -u)" -ne 0 ];then
	echo "Requires root!"
	exec sudo "$0" "$@"
	# Automatically rerun script with root
fi



# --- Logging


date="$(command -v date)"
tail="$(command -v tail)"

logFile="/var/log/updateroutine.log"
echo "Updating: $($date +'%a %e %b %4Y %H:%M')" >> $logFile
# Trim log file to 25 lines
# https://unix.stackexchange.com/a/310871
echo "$($tail -n 25 $logFile)" > $logFile


runHook() {
	baseDir="/etc/updateroutine/hooks"
	script="${basedir}/$1"
	if [ -x "$script" ]; then
		$script
	fi
}


# --- Pre apt routine

runHook pre-apt-hook




# --- Apt routine

apt="$(command -v apt)"


$apt update -y
$apt full-upgrade -y
$apt autoclean -y
$apt autoremove -y

# --- Post apt routine

runHook post-apt-hook


# --- Reboot

wall="$(command -v wall)"
time="1"
wall -n "System reboot in $time minute(s)"

shutdown -r +$time

