#!/bin/sh

# --- README --- #
# to run use 
# curl -fsSL https://raw.githubusercontent.com/MidnightRocket/linux-update-scripts/main/dnsproxy/debian/install | sudo sh
#
#
# --- --- ---

# POSIX compliant implementation
# https://stackoverflow.com/a/52586842
if [ "$(id -u)" -ne 0 ];then
	echo "Requires root!"
	exec sudo "$0" "$@"
	# Automatically rerun script with root
fi



mktemp="$(command -v mktemp)"
cat="$(command -v cat)"
curl="$(command -v curl)"
sha256sum="$(command -v sha256sum)"


TMPDIR="$($mktemp -d)"
trap 'rm -rf -- "$TMPDIR"' EXIT


# downloadFile url sha256sum save-path
downloadFile() {
	url="$1"
	shasum="$2"
	saveTo="$3"

	tmpFile="$($mktemp -p $TMPDIR)"
	$curl -f $1 -o $tmpFile
	
	if [ "$?" -ne 0 ]; then
		echo "Could not download file from: $url"
		exit 1
	fi
	
	echo "$shasum $tmpFile" | $sha256sum --status -c

	if [ "$?" -ne 0 ]; then
		echo "Failed to validate file from: $url"
		echo "File sha256sum mismatch!"
		echo "Wanted: $($sha256sum $tmpFile)"
		echo "But got: $shasum"
		exit 2
	fi
	
	echo "installing to: $saveTo"
	cp $tmpFile $saveTo
}

baseUrl="https://raw.githubusercontent.com/MidnightRocket/linux-update-scripts/main/dnsproxy/debian"



binDir="/usr/local/bin"



baseName="dnsproxy-wrapper"
file="$binDir/$baseName"
downloadFile ${baseUrl}/$baseName eb46f0aa2f566a7fc03cede1d1de52b37bec59ff25929b21b80277d7d498bc49 $file
# Must be executable
chmod 755 $file



# --- Create config directory

configDir="/etc/dnsproxy-configs"

if [ ! -d "$configDir" ]; then
	echo "Creating config dir in: $configDir"
	mkdir $configDir
	chmod 755 "$configDir"

	baseName="config.conf"
	file="$configDir/$baseName"
	downloadFile ${baseUrl}/configs/$baseName f8632941ee3dedf4d9eedd51aa200d7e06bb9c0810225a3763c14965e490f4cc $file
	# config.conf need to execute as it is a script
	chmod 755 $file


	baseName="upstream"
	file="$configDir/$baseName"
	downloadFile ${baseUrl}/configs/$baseName 2a243445c1845dd2b2cb32ec7f10033dd23e2eab63c885028e389c31a8bb86e3 $file
	baseName="fallback"
	file="$configDir/$baseName"
	downloadFile ${baseUrl}/configs/$baseName 97ddc81ac24901654b1ce226640d85bde5773d46969a6123dc24f9bafbcc7aa0 $file
fi




baseName="dnsproxy-downloader"
file="$TMPDIR/$baseName"
downloadFile ${baseUrl}/$baseName 2a48c69bcab5b41597a8ecd4069f4e385e219829ee67ca93e8196d7dab96d4d1 $file
# Must be executable
chmod 755 $file
dnsproxyDownloader="$file"






file="$($dnsproxyDownloader $TMPDIR)"
mv "$file" "$binDir/dnsproxy"








# --- Download systemd unit files
unitsDir="/etc/systemd/system"

serviceUnit="dnsproxy.service"
baseName="$serviceUnit"
file="$unitsDir/$baseName"
downloadFile ${baseUrl}/systemd/$baseName 9f4870d2752d4e28368444f96ac037658409451d46d978527cc6687e98098b93 $file



systemctl="$(command -v systemctl)"


if [ "$1" = "--update" ]; then
	$systemctl restart $serviceUnit
else 
	$systemctl enable --now $serviceUnit
fi



$systemctl status $serviceUnit

echo 
echo "To restart service use" 
echo "\tsudo systemctl restart $serviceUnit"
echo
echo "To view logs use: "
echo "\tsudo journalctl -f -b -u $serviceUnit"

