#!/bin/sh

# --- README --- #
# to run use 
# curl -fsSL https://raw.githubusercontent.com/MidnightRocket/linux-update-scripts/main/dnsproxy/debian/install | sudo sh
#
#
# --- --- ---

# POSIX compliant implementation
# https://stackoverflow.com/a/52586842
if [ "$(id -u)" -ne 0 ];then
	echo "Requires root!"
	exec sudo "$0" "$@"
	# Automatically rerun script with root
fi



mktemp="$(command -v mktemp)"
cat="$(command -v cat)"
curl="$(command -v curl)"
sha256sum="$(command -v sha256sum)"


TMPDIR="$($mktemp -d)"
trap 'rm -rf -- "$TMPDIR"' EXIT


# downloadFile url sha256sum save-path
downloadFile() {
	url="$1"
	shasum="$2"
	saveTo="$3"

	tmpFile="$($mktemp -p $TMPDIR)"
	$curl -f $1 -o $tmpFile
	
	if [ "$?" -ne 0 ]; then
		echo "Could not download file from: $url"
		exit 1
	fi
	
	echo "$shasum $tmpFile" | $sha256sum --status -c

	if [ "$?" -ne 0 ]; then
		echo "Failed to validate file from: $url"
		echo "File sha256sum mismatch!"
		echo "Wanted: $($sha256sum $tmpFile)"
		echo "But got: $shasum"
		exit 2
	fi
	
	echo "installing to: $saveTo"
	cp $tmpFile $saveTo
}

baseUrl="https://raw.githubusercontent.com/MidnightRocket/linux-update-scripts/main/dnsproxy/debian"





baseName="dnsproxy-wrapper"
file="/usr/local/bin/$baseName"
downloadFile ${baseUrl}/configs/$baseName 523ccc584b416aaab57bf63b203c7edd3064a5475ac82437f2f82d957753a37c $file
# Must be executable
chmod 755 $file



# --- Create config directory

configDir="/etc/dnsproxy-configs"

if [ ! -d "$configDir" ]; then
	echo "Creating config dir in: $configDir"
	mkdir $configDir
	chmod 755 "$configDir"

	baseName="config.conf"
	file="$configDir/$baseName"
	downloadFile ${baseUrl}/configs/$baseName 304ef9a69f0cdc8795f466fe40d2ca3b14609616eb98b706d749426b9eb85e73 $file
	# config.conf need to execute as it is a script
	chmod 755 $file


	baseName="upstream"
	file="$configDir/$baseName"
	downloadFile ${baseUrl}/configs/$baseName 2a243445c1845dd2b2cb32ec7f10033dd23e2eab63c885028e389c31a8bb86e3 $file
	baseName="fallback"
	file="$configDir/$baseName"
	downloadFile ${baseUrl}/configs/$baseName 97ddc81ac24901654b1ce226640d85bde5773d46969a6123dc24f9bafbcc7aa0 $file
fi











# --- Download systemd unit files
unitsDir="/etc/systemd/system"

serviceUnit="dnsproxy.service"
baseName="$serviceUnit"
file="$unitsDir/$baseName"
downloadFile ${baseUrl}/systemd/$baseName c9152f46513d12000ce1bfd6d31eccf80cd7c07c91c4d0b27eb3bb982430012d $file



systemctl="$(command -v systemctl)"
$systemctl enable --now $serviceUnit
$systemctl status $serviceUnit

echo 
echo "To restart service use" 
echo "\tsudo systemctl restart $serviceUnit"
echo
echo "To view logs use: "
echo "\tsudo journalctl -f -b -u $serviceUnit"

