#!/bin/sh

# --- README --- #
# to run use 
# curl -fsSL https://raw.githubusercontent.com/MidnightRocket/linux-update-scripts/main/dnsproxy/debian/install | sudo sh
#
#
# --- --- ---

# POSIX compliant implementation
# https://stackoverflow.com/a/52586842
if [ "$(id -u)" -ne 0 ];then
	echo "Requires root!"
	exec sudo "$0" "$@"
	# Automatically rerun script with root
fi



mktemp="$(command -v mktemp)"
cat="$(command -v cat)"
curl="$(command -v curl)"
sha256sum="$(command -v sha256sum)"


TMPDIR="$($mktemp -d)"
trap 'rm -rf -- "$TMPDIR"' EXIT


# downloadFile url sha256sum save-path
downloadFile() {
	url="$1"
	shasum="$2"
	saveTo="$3"

	tmpFile="$($mktemp -p $TMPDIR)"
	$curl -f $1 -o $tmpFile
	
	if [ "$?" -ne 0 ]; then
		echo "Could not download file from: $url"
		exit 1
	fi
	
	echo "$shasum $tmpFile" | $sha256sum --status -c

	if [ "$?" -ne 0 ]; then
		echo "Failed to validate file from: $url"
		echo "File sha256sum mismatch!"
		echo "Wanted: $($sha256sum $tmpFile)"
		echo "But got: $shasum"
		exit 2
	fi
	
	echo "installing to: $saveTo"
	cp $tmpFile $saveTo
}

baseUrl="https://raw.githubusercontent.com/MidnightRocket/linux-update-scripts/main/dnsproxy/debian"



binDir="/usr/local/bin"



baseName="dnsproxy-wrapper"
file="$binDir/$baseName"
downloadFile ${baseUrl}/$baseName 21f9fe6c8adf3cda609d85049dc3f0cb12e9525bd6a2adf86e40120b32a1ee9f $file
# Must be executable
chmod 755 $file



# --- Create config directory

configDir="/etc/dnsproxy-configs"

if [ ! -d "$configDir" ]; then
	echo "Creating config dir in: $configDir"
	mkdir $configDir
	chmod 755 "$configDir"

	baseName="config.conf"
	file="$configDir/$baseName"
	downloadFile ${baseUrl}/configs/$baseName f1c2929c92a11739c9aca6755b304852dd3f2cf708a204851b78406f1d337b4f $file
	# config.conf need to execute as it is a script
	chmod 755 $file


	baseName="upstream"
	file="$configDir/$baseName"
	downloadFile ${baseUrl}/configs/$baseName 2a243445c1845dd2b2cb32ec7f10033dd23e2eab63c885028e389c31a8bb86e3 $file
	baseName="fallback"
	file="$configDir/$baseName"
	downloadFile ${baseUrl}/configs/$baseName 97ddc81ac24901654b1ce226640d85bde5773d46969a6123dc24f9bafbcc7aa0 $file
fi




baseName="dnsproxy-downloader"
file="$TMPDIR/$baseName"
downloadFile ${baseUrl}/$baseName c7c97464f70b6969ee1b9abf8a0ba9d0376a9ed405e572012bbca4d9469c3013 $file
# Must be executable
chmod 755 $file
dnsproxyDownloader="$file"






file="$($dnsproxyDownloader $TMPDIR)"
mv "$file" "$binDir/dnsproxy"








# --- Download systemd unit files
unitsDir="/etc/systemd/system"

serviceUnit="dnsproxy.service"
baseName="$serviceUnit"
file="$unitsDir/$baseName"
downloadFile ${baseUrl}/systemd/$baseName c5e2e204d99050358737716f03e9933be5f903f48b792e0e4c773740a8fb7205 $file



systemctl="$(command -v systemctl)"


if [ "$1" = "--update" ]; then
	$systemctl stop $serviceUnit
	$systemctl daemon-reload
	$systemctl start $serviceUnit
else
	# Creates system user with no homedir, no login shell
	# And automatically creates matching group i.e. 'dnsproxy'
	useradd -s /usr/sbin/nologin --system -M dnsproxy

	# Make dnsproxy user owner of $configDir
	chown dnsproxy:dnsproxy -R $configDir


	$systemctl enable --now $serviceUnit
fi



$systemctl status $serviceUnit

echo 
echo "To restart service use" 
echo "\tsudo systemctl restart $serviceUnit"
echo
echo "To view logs use: "
echo "\tsudo journalctl -f -b -u $serviceUnit"

